import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
// @ts-ignore
import "./globals.css";

// Import Fredoka from Google Fonts
const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} antialiased`}>
        <div className="fixed top-4 right-4 bg-black/70 text-white px-4 py-2 rounded-lg text-sm z-50">
          <div className="text-xs opacity-75">
            Use ← → arrow keys to navigate pages
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
